# Generated by Django 4.2.10 on 2024-03-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='publiched_on',
            new_name='published_on',
        ),
    ]
